// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmgedEoc56f0NULweHqJIFzdFYldpUPxI',
    appId: '1:399843412995:web:e04f039d50fe7e43f75236',
    messagingSenderId: '399843412995',
    projectId: 'flutterfirebase-65852',
    authDomain: 'flutterfirebase-65852.firebaseapp.com',
    storageBucket: 'flutterfirebase-65852.appspot.com',
    measurementId: 'G-E41WQMEMC9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqEdUWNONTON1kBZFpioHZJ0udsEm4ncg',
    appId: '1:399843412995:android:475dd56b147e4880f75236',
    messagingSenderId: '399843412995',
    projectId: 'flutterfirebase-65852',
    storageBucket: 'flutterfirebase-65852.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZ0BUhQvvxZqHOZ1YeN2qfpH9psnp27LE',
    appId: '1:399843412995:ios:c3e4491885853573f75236',
    messagingSenderId: '399843412995',
    projectId: 'flutterfirebase-65852',
    storageBucket: 'flutterfirebase-65852.appspot.com',
    iosBundleId: 'com.ritplpro.flutterFirebaseapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZ0BUhQvvxZqHOZ1YeN2qfpH9psnp27LE',
    appId: '1:399843412995:ios:eb43ebb57d16cd53f75236',
    messagingSenderId: '399843412995',
    projectId: 'flutterfirebase-65852',
    storageBucket: 'flutterfirebase-65852.appspot.com',
    iosBundleId: 'com.ritplpro.flutterFirebaseapp.RunnerTests',
  );
}
